dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r test-requirements.txt
# command to run tests
jobs:
  include:
    - stage: check code style
      script: pycodestyle --show-source --show-pep8
    - stage: run unit test
      script:
        - pytest -v --cov . --cov-report term --cov-report html
after_success:
  - if [[ `python --version` =~ 3.7 ]]; then coveralls; fi
