dist: xenial
services:
  - docker
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r test-requirements.txt
before_script:
  - bash setup_container.sh start
# command to run tests
script:
  - pytest -v --cov . --cov-report term --cov-report html

after_success:
  - if [[ `python --version` =~ 3.7 ]]; then coveralls; fi
after_script:
  - bash setup_container.sh stop
